# List the available linters:
# go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest linters --no-config

# Run the last version:
# go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest run

# Documentation:
# https://golangci-lint.run/docs/configuration/file/
---
version: "2"

run:
  go: "1.25"

linters:
  default: standard

formatters:
  enable:
    - gofumpt
    - swaggo
